# 商品类别
type GoodsType {
   id:ID   
   name:String
   Business:Business
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    getGoodsType:[GoodsType]
}

extend type Mutation{
    saveGoodsType(goodsType:inputGoodsType):GoodsType
}

input inputGoodsType {   
   id:ID   
   name:String
   business_id:String
   isValid: Boolean
   updateAt:Date
   createAt:Date
}