# 积分统计
type Score {
   id:ID   
   trade_code:String
   Goods:Goods
   Business:Business
   User:User
   user_name:String
   start_time:String
   end_time:String
   complete_time:Date
   state:Boolean
   t_code:String   
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    getScore:[Score]
}

extend type Mutation{
    saveScore(score:inputScoreType):Score
}

input inputScoreType {   
   id:String 
   trade_code:String
   goods_id:String
   business_id:String
   user_id:String
   user_name:String
   start_time:String
   end_time:String
   complete_time:Date
   state:Boolean
   t_code:String   
   isValid: Boolean  
}