# 商品
type Goods {
   id:ID   
   name:String
   cost_score:Int
   rule:String
   explain:String
   count:Int
   trans_times:Int
   goods_type:String             
   imageSrc:String
   stock:Int
   limit:Int
   Business:Business
   GoodsType:GoodsType 
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    getGoods:[Goods]
}

extend type Mutation{
    saveGoods(goods:inputGoods):Goods
}

input inputGoods {   
   id:ID   
   name:String
   cost_score:Int
   rule:String
   explain:String
   count:Int
   trans_times:Int
   goods_type:String             
   imageSrc:String
   stock:Int
   limit:Int
   business_id:String
   goodsType_id:String 
   isValid: Boolean   
}