# 商品
type Goods {
   id:ID   
   name:String
   cost_score:Int
   rule:String
   explain:String
   count:Int
   trans_times:Int
   goods_type:String             
   imageSrc:String
   stock:Int
   limit:Int
   Business:Business
   GoodsType:GoodsType 
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有商品
    getGoods:[Goods]
    # 根据ID查找问答
    getGoodsById(id:String):Goods
    # 分页查找
    getGoodsPage(pageIndex: Int, pageSize: Int,goods:searchGoods): [Goods]
    # 查找分页总数
    getGoodsCount(goods:searchGoods):Int
    # 根据条件查找
    getGoodsWhere(goods:searchGoods): [Goods] 
}

extend type Mutation{
    # 添加修改商品
    saveGoods(goods:inputGoods):Goods
    # 删除商品
    deleteGoods(id:String):Boolean
}

input inputGoods {   
   id:ID   
   name:String
   cost_score:Int
   rule:String
   explain:String
   count:Int
   trans_times:Int
   goods_type:String             
   imageSrc:String
   stock:Int
   limit:Int
   business_id:String
   goodsType_id:String 
   isValid: Boolean   
}


input searchGoods{
    id:Json
    name:Json
}