# 商品
type Goods {
    id:ID   
    Business:Business
    GoodsType:GoodsType
    Images: [File]
    name:String
    score:Int
    ruler:String
    explain:String
    stock:Int
    times:Int    
    validTime:Float
    sortIndex:Float
    isValid:Boolean
    updateAt:Date
    createAt:Date
}

extend type Query{
    # 查询所有商品
    getGoods:[Goods]
    # 根据ID查找问答
    getGoodsById(id:String):Goods
    # 分页查找
    getGoodsPage(pageIndex: Int, pageSize: Int,goods:searchGoods): [Goods]
    # 分页查找（前台）
    getGoodsPageM(pageIndex: Int, pageSize: Int,goods:searchGoods,sort:sortObj): [Goods]
    # 查找分页总数
    getGoodsCount(goods:searchGoods):Int
    # 根据条件查找
    getGoodsWhere(goods:searchGoods): [Goods] 
}

extend type Mutation{
    # 添加修改商品
    saveGoods(goods:inputGoods):Goods
    # 删除商品
    deleteGoods(id:String):Boolean
}

input inputGoods {   
    id:String  
    businessId:String
    goodsTypeId:String
    name:String
    score:Int
    ruler:String
    explain:String
    stock:Int
    times:Int
    imageIds: [String]
    validTime:Float
    sortIndex:Float
    isValid:Boolean    
    updateAt:Date
    createAt:Date
}

input searchGoods{
    id:Json
    name:RegExp
    businessId:Json    
    isValid:Boolean
    goodsTypeId:Json
}

input sortObj {
    times:Int    
    sortIndex:Int
    score:Int
    goodsTypeId:String
}