# 积分统计
type Transaction {
   id:ID   
   code:String
   Goods:Goods
   Business:Business
   User:User
   startTime:Date
   endTime:Date
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有
    getTransaction:[Transaction]
    # 根据ID查找问答
    getTransactionById(id:String):Transaction
    # 分页查找
    getTransactionPage(pageIndex: Int, pageSize: Int,transaction:searchTransactionType): [Transaction]
    # 查找分页总数
    getTransactionCount(transaction:searchTransactionType):Int
    # 根据条件查找
    getTransactionWhere(transaction:searchTransactionType): [Transaction] 
}

extend type Mutation{
    # 添加修改交易
    saveTransaction(transaction:inputTransaction):Transaction
    # 删除交易
    deleteTransaction(id:String):Boolean
}

input inputTransaction {   
   id:String  
   code:String
   goodsId:String
   businessId:String
   userId:String
   startTime:Date
   endTime:Date  
}

input searchTransactionType{
    id:Json
    name:Json
    t_code:Json
}