# 积分统计
type Transaction {
   id:ID   
   code:String
   Goods:Goods
   Business:Business
   User:User
   state:Int      
   endTime:Date
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有
    getTransaction:[Transaction]
    # 根据ID查找问答
    getTransactionById(id:String):Transaction
    # 分页查找
    getTransactionPage(pageIndex: Int, pageSize: Int,transaction:searchTransaction): [Transaction]
    # 查找分页总数
    getTransactionCount(transaction:searchTransaction):Int
    # 根据条件查找
    # getTransactionWhere(transaction:searchTransaction): [Transaction]         
    doTransact(code:String):Int
}

extend type Mutation{
    # 添加修改交易
    # saveTranUser:Boolean
    # saveTranBusiness:Boolean    
    # saveTranGoods(userId:String, businessId:String, goodsId:String):Boolean           
    # 删除交易
    # deleteTransaction(id:String):Boolean
    # 添加交易
    saveTransaction(userId:String, businessId:String, goodsId:String):Boolean
}

input inputTransaction {   
   id:String  
   code:String
   goodsId:String
   businessId:String
   userId:String
   state:Int      
   endTime:Date  
}

input searchTransaction{
    id:Json
    name:Json
    code:Json
    goodsId:Json
    state:Int
    endTime:Json
}   