#玩家用户表
type Play {
    id:Int
    #微信ID
    weixin:String
    deviceMac:String
    #微信名
    name:String
    forbid:Boolean
    #微信头像
    image:String
    sex:Int
    state:Int
    #房卡数量
    cardNum:Int
    #最后登录时间
    lastLoginTime:Date
    #登录IP地址
    lastLoginIp:String
    updateTime:Date
    createTime:Date
    deleteTime:Date
    platform:String
    appVersion:String
    resourceVersion:String
    #群主ID
    code:String
}

extend type Query {
    # 查找所有玩家
    getPlays: [Play]
    # 根据ID查找玩家
    getPlayById(id:String):User
    # 分页查找玩家
    getPlayPage(pageIndex: Int, pageSize: Int,where:String): [Play]
    # 查找分页玩家总数
    getPlayCount(where:String):Int
    # 根据条件查找
    getPlayWhere(where:String): [Play]
}

extend type Mutation {
   
}
