#玩家用户表
type Player {
    id:ID!
    #微信ID
    weixin:String
    deviceMac:String
    #微信名
    name:String
    forbid:Boolean
    #微信头像
    image:String
    sex:Int
    state:Int
    #房卡数量
    cardNum:Int
    #最后登录时间
    lastLoginTime:Date
    #登录IP地址
    lastLoginIp:String
    updateTime:Date
    createTime:Date
    deleteTime:Date
    platform:String
    appVersion:String
    resourceVersion:String
    #群主ID
    code:String
}

extend type Query {
    # 查找所有玩家
    getPlayers: [Player]
    # 根据ID查找玩家
    getPlayerById(id:String):Player
    # 分页查找玩家
    getPlayerPage(pageIndex: Int, pageSize: Int,where:String,order:String): [Player]
    # 查找分页玩家总数
    getPlayerCount(where:String):Int
    # 根据条件查找
    getPlayerWhere(where:String,order:String): [Player]
}

extend type Mutation {
    #修改用户房卡
    updatePlayerCard(id:String,cardNum:Int): Boolean
}
