# 商家
type Business {
   id:ID
   name:String
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    getBusiness:[Business]
}

extend type Mutation{
    saveBusiness(business:inputBusiness):Business
}

input inputBusiness {   
   name:String  
   isValid: Boolean   
}