# 商家
type Business {
   id:ID
   User:User
   name:String
   phone_num:String
   address:String
   b_hours:String  
   brief:String
   score:Int
   imageSrc: String
   trans_times:Int
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    getBusiness:[Business]
}

extend type Mutation{
    saveBusiness(business:inputBusiness):Business
}

input inputBusiness { 
   id:String     
   user_id:String
   name:String
   phone_num:String
   address:String
   b_hours:String  
   brief:String
   score:Int
   imageSrc: String
   trans_times:Int
   isValid: Boolean   
}