# 系统用户表
type User {
    id: ID!
    # 用户登录名
    username: String
    # 姓名
    name: String
    # 邮件
    email:String
    # 密码
    password:String
    # 创建时间
    createAt:Date
    # 修改时间
    updateAt:Date
    #用户角色
    Role:Role
    #是否有效
    isValid:Boolean
    #用户资料
    Profile:Profile
}

extend type Query {
    # 查找所有用户
    getUsers: [User]
    # 根据ID查找用户
    getUserById(id:String):User
    # 分页查找
    getUserPage(pageIndex: Int, pageSize: Int,user:searchUser): [User]
    # 查找分页总数
    getUserCount(user:searchUser):Int
    # 根据条件查找
    getUserWhere(user:searchUser): [User]
    # 用户登录
    login (username:String!,password:String!): User
    # 用户退出
    logOut:Boolean,
    #当前登录用户
    currentUser:User
   
}

extend type Mutation {
    # 创建用户|修改用户
    saveUser(user:inputUser):User
     # 删除用户
    deleteUser(id:String):Boolean
}

input inputUser{
    id:String
    username: String
    name: String
    email:String
    password:String
    roleId:String
    profileId:String
    isValid:Boolean
}

input searchUser{
    username:Json
    roleId:Json
    email:Json
    name:Json
}