# 查询
type Query {
	dummy: Boolean
}

# 变更
type Mutation {
	dummy: Boolean
}

# 文件
type File {
	id: String
	fieldname: String
	originalname: String
	encoding: String
	mimetype: String
	destination: String
	filename: String
	path: String
	size: Float
	meta: Meta
}

type Meta {
	revision: Int
	created: Float
	version: Int
}

# 日期类型
scalar Date

# 正则表达式类型
scalar RegExp

#Json 格式
scalar JsonObject
