# 广告
type Advertm {
   id:ID
   title:String
   type:String
   link:String      
   Images: [File]
   explain:String   
   startDate:Date
   endDate:Date   
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有广告
    getAdvertm:[Advertm]
    # 根据ID查找广告
    getAdvertmById(id:String):Advertm
    # 分页查找
    getAdvertmPage(pageIndex: Int, pageSize: Int,advertm:searchAdvertm): [Advertm]
    # 查找分页总数
    getAdvertmCount(advertm:searchAdvertm):Int
    # 根据条件查找
    getAdvertmWhere(advertm:searchAdvertm): [Advertm]    
}

extend type Mutation{
    # 添加修改广告
    saveAdvertm(advertm:inputAdvertm):Advertm
    # 删除广告
    deleteAdvertm(id:String):Boolean
}

input inputAdvertm { 
   id:String
   title:String
   type:String
   link:String      
   imageIds: [String]
   explain:String   
   startDate:Date
   endDate:Date   
   isValid: Boolean   
}

input searchAdvertm{
    id:JsonObject
    title:JsonObject
}