# 广告
type Adverm {
   id:ID
   name:String
   link:String   
   type:String
   desc:String
   imageSrc:String
   startDate:Date
   endDate:Date   
   isValid: Boolean
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有广告
    getAdvertm:[Adverm]
    # 根据ID查找广告
    getAdvertmById(id:String):Adverm
    # 分页查找
    getAdvertmPage(pageIndex: Int, pageSize: Int,advertm:searchAdvertm): [Adverm]
    # 查找分页总数
    getAdvertmCount(advertm:searchAdvertm):Int
    # 根据条件查找
    getAdvertmWhere(advertm:searchAdvertm): [Adverm]    
}

extend type Mutation{
    # 添加修改广告
    saveAdvertm(adverm:inputAdverm):Adverm
    # 删除广告
    deleteAdvertm(id:String):Boolean
}

input inputAdverm { 
   id:String
   name:String
   link:String   
   type:String
   desc:String
   imageSrc:String
   startDate:Date
   endDate:Date   
   isValid: Boolean     
}

input searchAdvertm{
    id:JsonObject
    name:JsonObject
}